FROM python:3.7

RUN pip install --upgrade devpi-server devpi-client devpi-web

EXPOSE 3141

VOLUME /data

ENV HOME /data
WORKDIR /data

COPY devpi_run.bash /devpi_run.bash
RUN chmod +x /devpi_run.bash

CMD ["/devpi_run.bash"]
